const ProductList = [
	{
		id: "1",
		name: "Apple iPhone 13 Pro (128 GB) - Alpine Green",
		img: "https://ik.imagekit.io/5yc2yhl2a/images/mobiles/Apple_iPhone13Po_128_forestGreen_QkXgKMC4m.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1652088316154",
		no_of_ratings: "536",
		answered_questions: "94",
		rating: 4.5,
		price: 119900,
		sizeName: "128GB",
		colour: "Alpine Green",
		emi: "5,644",
		soldby: "Appario Retail Private Ltd",
		delivery: "Wednessday, May 18",
		status: "In stock",
		about: [
			"15 cm (6.1-inch) Super Retina XDR display with ProMotion for a faster, more responsive feel",
			"Cinematic mode adds shallow depth of field and shifts focus automatically in your videos",
			"Pro camera system with new 12MP Telephoto, Wide and Ultra Wide cameras; LiDAR Scanner; 6x optical zoom range; macro photography; Photographic Styles, ProRes video, Smart HDR 4, Night mode, Apple ProRAW, 4K Dolby Vision HDR recording",
			"12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording",
			"A15 Bionic chip for lightning-fast performance",
			"Up to 22 hours of video playback",
			"Durable design with Ceramic Shield",
			"Industry-leading IP68 water resistance",
			"iOS 15 packs new features to do more with iPhone than ever before",
			"Supports MagSafe accessories for easy attachment and faster wireless charging",
		],
	},
	{
		id: "2",
		name: "Apple iPhone 13 (128GB) - Midnight",
		img: "https://ik.imagekit.io/5yc2yhl2a/images/mobiles/Apple_iPhone13_128_midnight_yxXWw9Wbr.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1652087586208",
		no_of_ratings: "3,932",
		answered_questions: "269",
		rating: 4.5,
		price: 69900,
		sizeName: "128GB",
		colour: "Midnight",
		emi: "3,290",
		soldby: "Appario Retail Private Ltd",
		delivery: "Monday, May 16",
		status: "In stock",
		about: [
			"15 cm (6.1-inch) Super Retina XDR display",
			"Cinematic mode adds shallow depth of field and shifts focus automatically in your videos",
			"Advanced dual-camera system with 12MP Wide and Ultra Wide cameras; Photographic Styles, Smart HDR 4, Night mode, 4K Dolby Vision HDR recording",
			"12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording",
			"A15 Bionic chip for lightning-fast performance",
			"Up to 19 hours of video playback",
			"Durable design with Ceramic Shield",
			"Industry-leading IP68 water resistance",
			"iOS 15 packs new features to do more with iPhone than ever before",
			"Supports MagSafe accessories for easy attachment and faster wireless charging",
		],
	},
	{
		id: "3",
		name: "Apple iPhone 13 (128GB) - (Product) RED",
		img: "https://ik.imagekit.io/5yc2yhl2a/images/mobiles/Apple_iPhone13_128_red_buDAvEYjT.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1652087586527",
		no_of_ratings: "3,932",
		answered_questions: "269",
		rating: 4.5,
		price: 70990,
		sizeName: "128GB",
		colour: "RED",
		emi: "3,342",
		soldby: "Appario Retail Private Ltd",
		delivery: "Monday, May 16",
		status: "In stock",
		about: [
			"15 cm (6.1-inch) Super Retina XDR display",
			"Cinematic mode adds shallow depth of field and shifts focus automatically in your videos",
			"Advanced dual-camera system with 12MP Wide and Ultra Wide cameras; Photographic Styles, Smart HDR 4, Night mode, 4K Dolby Vision HDR recording",
			"12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording",
			"A15 Bionic chip for lightning-fast performance",
			"Up to 19 hours of video playback",
			"Durable design with Ceramic Shield",
			"Industry-leading IP68 water resistance",
			"iOS 15 packs new features to do more with iPhone than ever before",
			"Supports MagSafe accessories for easy attachment and faster wireless charging",
		],
	},
	{
		id: "4",
		name: "Apple iPhone 12 Pro (512GB) - Pacific Blue",
		img: "https://ik.imagekit.io/5yc2yhl2a/images/mobiles/apple-iphone-12-pro-dummyapplefsn-original-imafwgbrzxg3nggd_K7qDL3X8Z.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1652088692348",
		no_of_ratings: "1,554",
		answered_questions: "382",
		rating: 4.5,
		price: 131800,
		sizeName: "512GB",
		colour: "Pacific Blue",
		emi: "4,782",
		soldby: "Appario Retail Private Ltd",
		delivery: "Monday, May 16",
		status: "In stock",
		about: [
			"6.1-inch (15.5 cm diagonal) Super Retina XDR display",
			"Ceramic Shield, tougher than any smartphone glass",
			"A14 Bionic chip, the fastest chip ever in a smartphone",
			"Pro camera system with 12MP Ultra Wide, Wide and Telephoto cameras; 4x optical zoom range; Night mode, Deep Fusion, Smart HDR 3, Apple ProRAW, 4K Dolby Vision HDR recording",
			"LiDAR Scanner for improved AR experiences, Night mode portraits",
			"12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording",
			"Industry-leading IP68 water resistance",
			"Supports MagSafe accessories for easy attach and faster wireless charging",
			"iOS with redesigned widgets on the Home screen, all-new App Library, App Clips and more",
		],
	},
	{
		id: "5",
		name: "Apple iPhone 12 (128GB) - Blue",
		img: "https://ik.imagekit.io/5yc2yhl2a/images/mobiles/Apple_iPhone12_128_blue_09dUqkCBF.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1652087586184",
		no_of_ratings: "13,047",
		answered_questions: "1000+",
		rating: 4.5,
		price: 59900,
		sizeName: "128GB",
		colour: "Blue",
		emi: "2,820",
		soldby: "Darshita Electronics",
		delivery: "Sunday, May 22",
		status: "In stock",
		about: [
			"6.1-inch (15.5 cm diagonal) Super Retina XDR display",
			"Ceramic Shield, tougher than any smartphone glass",
			"A14 Bionic chip, the fastest chip ever in a smartphone",
			"Advanced dual-camera system with 12MP Ultra Wide and Wide cameras; Night mode, Deep Fusion, Smart HDR 3, 4K Dolby Vision HDR recording",
			"12MP TrueDepth front camera with Night mode, 4K Dolby Vision HDR recording",
			"Industry-leading IP68 water resistance",
			"Supports MagSafe accessories for easy attach and faster wireless charging",
			"iOS with redesigned widgets on the Home screen, all-new App Library, App Clips and more",
		],
	},
	{
		id: "6",
		name: "Apple iPhone 11 (128GB) - Purple",
		img: "https://ik.imagekit.io/5yc2yhl2a/images/mobiles/iphone11_128_purple_E8LoM9dDs.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1652089037716",
		no_of_ratings: "43,111",
		answered_questions: "1000+",
		rating: 4.5,
		price: 48000,
		sizeName: "128GB",
		colour: "Purple",
		emi: "4,310",
		soldby: "Darshita Electronics",
		delivery: "Monday, May16",
		status: "In stock",
		about: [
			"128 GB ROM",
			"15.49 cm (6.1 inch) Liquid Retina HD Display",
			"12MP + 12MP | 12MP Front Camera",
			"A13 Bionic Chip Processor",
			"1400:1 Contrast Ratio (Typical), True Tone Display, Wide Colour Display (P3), Haptic Touch",
			"625 nits Max Brightness (Typical), Fingerprint Resistant Oleophobic Coating",
			"Support for Display of Multiple Languages and Characters Simultaneously",
		],
	},
	{
		id: "7",
		name: "Apple iPhone XR (128GB) - Coral",
		img: "https://ik.imagekit.io/5yc2yhl2a/images/mobiles/iphone_XR_128_orange_hrYNmGuGt.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1652089258572",
		no_of_ratings: "7,241",
		answered_questions: "517",
		rating: 4.5,
		price: 42999,
		sizeName: "128GB",
		colour: "Coral",
		emi: "2,024",
		soldby: "Darshita Electronics",
		delivery: "Monday, May16",
		status: "In stock",
		about: [
			"6.1-inch (15.5 cm diagonal) Liquid Retina HD LCD display",
			"Water and dust resistant (1 meter for up to 30 minutes, IP67)",
			"Single 12MP Wide camera with Portrait mode, Portrait Lighting, Depth Control, Smart HDR, and 4K video up to 60fps",
			"7MP TrueDepth front camera system with Portrait mode, Portrait Lighting, Depth Control, and 1080p video",
			"Face ID for secure authentication",
			"A12 Bionic with second-generation Neural Engine",
			"Fast-charge capable",
			"Wireless charging",
			"As part of our efforts to reach our environmental goals, iPhone no longer includes a power adapter or EarPods. Please use your existing Apple power adapter and headphones or buy these accessories separately",
			"iOS 14 with redesigned widgets on the Home screen, all-new App Library, App Clips, and more",
		],
	},
	{
		id: "8",
		name: "Samsung Galaxy S22 Ultra 5G  (Phantom Black, 12GB, 512GB Storage)",
		img: "https://ik.imagekit.io/5yc2yhl2a/images/mobiles/galaxyS22ultraBlack_bAsqEMHgb.jpeg?ik-sdk-version=javascript-1.4.3&updatedAt=1652089866568",
		no_of_ratings: "8,568",
		answered_questions: "558",
		rating: 5,
		price: 118999,
		sizeName: "12GB/512GB",
		colour: "Phantom Black",
		emi: "5,602",
		soldby: "Appario Retail Private Ltd",
		delivery: "Monday, May 16",
		status: "In stock",
		about: [
			"The first Galaxy S with embedded S Pen. Write comfortably like pen on paper, turn quick notes into legible text and use Air Actions to control your phone remotely. Improved latency in Samsung Notes makes every pen stroke feel as natural as ink on paper — and you can convert those hastily written ideas into legible text.",
			"5G Ready powered by Galaxy’s first 4nm processor. Our fastest, most powerful chip ever. That means, a faster CPU and GPU compared to Galaxy S21 Ultra. It’s an epic leap for smartphone technology.",
			"The Dynamic AMOLED 2x display improves outdoor visibility with up to 1750 nits in peak brightness.* And the 120Hz adaptive refresh rate keeps the scroll smooth, adjusting to what's on screen for an optimized view.",
			"Our most advanced Pro-grade Camera yet, packing the power of a professional's kit in one handheld device. Also lets you make your nights epic with Nightography: The sensor pulls in more light, the Super Clear Lens tones down lens flare, and fast-acting AI delivers near-instant intelligent processing.",
		],
	},
	{
		id: "9",
		name: "Samsung Galaxy S22 Plus 5G (Green, 8GB, 256GB Storage)",
		img: "https://ik.imagekit.io/5yc2yhl2a/images/mobiles/galaxyS22plus_w1GtsZuMP.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1652089613846",
		no_of_ratings: "12,568",
		answered_questions: "86",
		rating: 4,
		price: 88990,
		sizeName: "8GB/256GB",
		colour: "Green",
		emi: "4,189",
		soldby: "Appario Retail Private Ltd",
		delivery: "Wednessday, May 18",
		status: "In stock",
		about: [
			"Pro-grade Camera that lets you make your nights epic with Nightography: It’s our brightest innovation yet. The sensor pulls in more light, the Super Clear Glass dials down lens flare, and fast-acting AI delivers near-instant intelligent processing.",
			"VisionBooster outshines the sun: Stunning 120Hz Dynamic AMOLED 2X display is crafted specifically for high outdoor visibility, keeping the view clear in bright daylight.",
			"4nm processor, our fastest chip yet: Our fastest, most powerful chip ever. That means, a faster CPU and GPU compared to Galaxy S21 Ultra. It’s an epic leap for smartphone technology.",
			"Sleek design in a range of colors lets you express yourself how you like. The slim bezels flow into a symmetrical polished frame for an expansive, balanced display. Corning Gorilla Glass Victus+ on the screen and back panels.",
		],
	},
	{
		id: "10",
		name: "Samsung Galaxy S22 5G (Pink Gold, 8GB, 128GB Storage)",
		img: "https://ik.imagekit.io/5yc2yhl2a/images/mobiles/galaxyS22Pink_Yplt1gplP.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1652090523118",
		no_of_ratings: "14,256",
		answered_questions: "97",
		rating: 3.5,
		price: 72999,
		sizeName: "8GB/128GB",
		colour: "Pink Gold",
		emi: "3,436",
		soldby: "Appario Retail Private Ltd",
		delivery: "Saturday, May 21",
		status: "In stock",
		about: [
			"Pro-grade Camera that lets you make your nights epic with Nightography: It’s our brightest innovation yet. The sensor pulls in more light, the Super Clear Glass dials down lens flare, and fast-acting AI delivers near-instant intelligent processing.",
			"VisionBooster outshines the sun: Stunning 120Hz Dynamic AMOLED 2X display is crafted specifically for high outdoor visibility, keeping the view clear in bright daylight.",
			"4nm processor, our fastest chip yet: Our fastest, most powerful chip ever. That means, a faster CPU and GPU compared to Galaxy S21 Ultra. It’s an epic leap for smartphone technology.",
			"Sleek design in a range of colors lets you express yourself how you like. The slim bezels flow into a symmetrical polished frame for an expansive, balanced display. Corning Gorilla Glass Victus+ on the screen and back panels.",
		],
	},
	{
		id: "11",
		name: "Google Pixel 6 Pro 5G (Stromy Black, 12GB RAM, 256GB Storage)",
		img: "https://ik.imagekit.io/5yc2yhl2a/images/mobiles/pixel6Pro_gdfEB75_4.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1652090846794",
		no_of_ratings: "359",
		answered_questions: "48",
		rating: 4,
		price: 104000,
		sizeName: "12GB/256GB",
		colour: "Stromy Black",
		emi: "4,896",
		soldby: "Gautam labdhi technology",
		delivery: "Friday, May 20",
		status: "In stock",
		about: [
			"Unlocked Android cell phone gives you the flexibility to change carriers and choose your own data plan[1]; the new, redesigned Pixel 6 Pro is the smartest and fastest Pixel yet",
			"The powerful Google Tensor processor is the first processor designed by Google and made for Pixel; takes performance to a whole new level Advanced camera system with wide and ultrawide lenses, 4x optical zoom, and a main sensor that captures 150% more light",
		],
	},
	{
		id: "12",
		name: "Google Pixel 6 5G (Kinda Coral, 8GB RAM, 128GB Storage)",
		img: "https://ik.imagekit.io/5yc2yhl2a/images/mobiles/pixel6_FTwr5UiXpw.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1652091065801",
		no_of_ratings: "111",
		answered_questions: "121",
		rating: 4,
		price: 45890,
		sizeName: "8GB/128GB",
		colour: "Kinda Coral",
		emi: "2,160",
		soldby: "world bazzar",
		delivery: "Saturday, May 21",
		status: "In stock",
		about: [
			"Pixel’s 50 megapixel rear camera captures 150% more light for photos with richer colors and more detail",
			"Unlocked Android 5G phone gives you the flexibility to change carriers and choose your own data plan[1]; Pixel 6 is fast, smart, and secure, and adapts to you",
			"The powerful Google Tensor processor is the first processor designed by Google and made for Pixel; it keeps your phone fast, your games rich, and your personal info safe",
			"Professional tools like Magic Eraser[3], Motion Mode, and Portrait Mode keep your photos sharp, accurate, and focused",
			"Pixel’s fast charging[4] all day battery adapts to you and saves power for apps you use most[5]",
			"Privacy and protection are built into your Pixel smartphone; backed by the Titan M2 security chip, 5 years of updates, and the security core[6]",
			"New Pixel experience is more modern and intuitive, with colors that reflect your personal style; the At a Glance feature shows you the apps and info you need when you need it, like a boarding pass before a flight",
		],
	},
	{
		id: "13",
		name: "OnePlus 10 Pro 5G (Volcanic Black, 8GB RAM, 128GB Storage)",
		img: "https://ik.imagekit.io/5yc2yhl2a/images/mobiles/Oneplus_10Pro_5G_o8RFOBULF8.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1653311873821",
		no_of_ratings: "933",
		answered_questions: "127",
		rating: 4,
		price: 66999,
		sizeName: "8GB/128GB",
		colour: "Volcaninc Black",
		emi: "3,154",
		soldby: "Darshita Etel",
		delivery: "Wednesday, May 25",
		status: "In Stock",
		about: [
			"Camera: 48MP Main Camera with Sony IMX 789 Lens (OIS enabled), 50MP Ultra-wide angle camera & 8MP Tele photo lens; Front (Selfie) Camera: 32MP; Flash: Dual LED",
			"Camera Features: Hasselblad Camera for Mobile, Nightscape, Ultra HDR, Smart Scene Recognition, Portrait Mode, Pro Mode, Panorama Mode, Tilt-Shift mode, Long Exposure Mode, 150° Wide angle Mode, Dual-View Video, Movie Mode, Xpan Mode, Filters, Super Stable, Video Nightscape, Video HDR, Video Portrait, Focus Tracking, Timelapse",
			"Display: 6.7 Inches; 120 Hz QHD+ Fluid AMOLED with LTPO; Resolution: 3216 x 1440; Aspect Ratio: 20:9",
			"Display Features: Nature tone display, Video colour enhancer, Colour personalization, Colour vision enhancement, Auto brightness, Manual brightness, Screen colour temperature, Bright HDR video mode, Night Mode, Multi-brightness colour calibration, Vibrant Colour Effect Pro, Ultra high resolution video",
			"Operating System: Oxygen OS based on Android 12",
			"Processor: Qualcomm Snapdragon 8 Gen 1",
			"Battery & Charging: 5000 mAh with 80W SuperVOOC",
			"In-Display Fingerprint Sensor",
			"Alexa Hands-Free capable: Download the Alexa app to use Alexa hands-free. Play music, make calls, hear news, open apps, navigate, and more, all using just your voice, while on-the-go.",
			"Connector type: usb type c",
		],
	},
	{
		id: "14",
		name: "OnePlus 10R 5G (Forest Green, 12GB RAM, 256GB Storage, 80W SuperVOOC)",
		img: "https://ik.imagekit.io/5yc2yhl2a/images/mobiles/Oneplus_10R_5G_5ekQqozot.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1653312421069",
		no_of_ratings: "159",
		answered_questions: "47",
		rating: 4,
		price: 42999,
		sizeName: "12GB/256GB",
		colour: "Forest Green",
		emi: "2,024",
		soldby: "Darshita Electronics",
		delivery: "Wednesday, May 25",
		status: "In Stock",
		about: [
			"Camera: 50MP Main Camera with Sony IMX766 and 2MP Macro Camera with Dual LED Flash; 16MP Front (Selfie) Camera with Sony IMX471",
			"Camera Features: Nightscape2.0, Super Macro, UltraShot HDR, Smart Scene Recognition, Portrait mode, Pro mode, Panorama, Tilt-shift mode, Focus Peaking, Filters, Video Nightscape, Video HDR, Video Portrait Timelapse, Hyperlapse Mode",
			"Display: 6.7 Inches; 120 Hz IRIS Display; Resolution: 2400 X 1080 pixels 394 ppi; Aspect Ratio: 20:9",
			"Display Features: Hyper Touch Mode, Reading Mode, Night Mode, Eye Comfort Mode, Auto brightness",
			"Operating System: Oxygen OS based on Android 12",
			"Processor: MTK D8100 Max",
			"Battery & Charging: 5000 mAh with 80W SuperVOOC",
			"In-Display Fingerprint Sensor",
			"Alexa Hands-Free capable: Download the Alexa app to use Alexa hands-free. Play music, make calls, hear news, open apps, navigate, and more, all using just your voice, while on-the-go.",
		],
	},
	{
		id: "15",
		name: "OnePlus 9 5G (Astral Black, 12GB RAM, 256GB Storage)",
		img: "https://ik.imagekit.io/5yc2yhl2a/images/mobiles/Oneplus_9_5g_FRC3_j1PP.webp?ik-sdk-version=javascript-1.4.3&updatedAt=1653312800619",
		no_of_ratings: "28,666",
		answered_questions: "1000+",
		rating: 4.5,
		price: 42999,
		sizeName: "12GB/256GB",
		colour: "Astral Black",
		emi: "2,024",
		soldby: "#GreenMobiles",
		delivery: "Wednesday, May 25",
		status: "In Stock",
		about: [
			"Rear Triple Camera Co-Developed by Hasselblad, 48 MP Main camera, 50 MP Ultra Wide Angle Camera with Free Form Lens, 2 MP Monochorme Lens. Also comes with a 16 MP Front Camera",
			"Qualcomm Snapdragon 888 Processor with Adreno 660 GPU",
			"6.55 Inches Fluid AMOLED Display with 120Hz refresh rate",
			"OnePlus Oxygen OS based on Andriod 11",
			"Comes with 4500 mAh Battery with 65W Wired Charging",
			"Hands-Free access to Alexa: Alexa on your phone lets you make phone calls, open apps, control smart home devices, access the library of Alexa skills, and more using just your voice while on-the-go. Download the Alexa app and complete hands-free setup to get started. Just ask - and Alexa will respond instantly",
		],
	},
];

export default ProductList;
